### ISSUE TITLE
Short presentation

### ISSUE THREAD

**Issue by Nebraw** [XXII-AI/Lours#31]
Hello, 
I'm trying to share this great lib around me, but I noticed something. You haven't made a short presentation (except during meetup) of what Lours is, what it is, its purpose, its goal.

I think it would be nice for new users, or people who found your repository without knowing what it is, to have a short introduction in the read me.

**Comment by ClementPinard** [comment]
Hi, thank you for your interest in Lours !

Here is the presentation that we did for the meetup (modulo some modification)

**Comment by ClementPinard** [comment]
Hi, I have now added the presentation directly on the README landing page. Hope it will be good for you !
